//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_projektzaliczeniowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int Id { get; set; }
        public string data { get; set; }
        public int Usługa_id { get; set; }
        public int Pracownik_id { get; set; }
        public int Klient_id { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Zabieg Zabieg { get; set; }
    }
}
